export const REQUEST_QUIZ_PENDING = "REQUEST_QUIZ_PENDING";
export const REQUEST_QUIZ_SUCCESS = "REQUEST_QUIZ_SUCCESS";
export const REQUEST_QUIZ_FAILED = "REQUEST_QUIZ_FAILED";
export const CORRECT_ANSWER = "CORRECT_ANSWER";
export const WRONG_ANSWER = "WRONG_ANSWER";

export const REQUEST_ADVICE_PENDING = "REQUEST_ADVICE_PENDING";
export const REQUEST_ADVICE_SUCCESS = "REQUEST_ADVICE_SUCCESS";
export const REQUEST_ADVICE_FAILED = "REQUEST_ADVICE_FAILED";